module.exports = {
  ROLE: {
    USER: "user",
    MANAGER: "manager",
  },
  SUCCESS: 200,
  BAD_REQUEST: 400,
  PAGE_NOT_FOUND: 404,
  UNAUTHORIZED: 401,
  INTERNAL_SERVER: 500,
  NOT_ACCEPTABLE: 406,
  DATA_CONFLICT: 409,
  CREATED: 201,
  FAIL: 400,
  ACTIVE: "1",
  INACTIVE: "0",
  DELETE: "2",
};
